var eventsList = const [
  [
    //DAY 1
    {
      ////index:0
      'eventName': "Brain Test",
      'imagePath': "assets/images/eventsPosters/image_04.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:1
      'eventName': "Debate",
      'imagePath': "assets/images/eventsPosters/image_03.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:2
      'eventName': "Just a minute (JAM)",
      'imagePath': "assets/images/eventsPosters/image_02.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:3
      'eventName': "Twist a tale",
      'imagePath': "assets/images/eventsPosters/image_01.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:4
      'eventName': "Connected",
      'imagePath': "assets/images/eventsPosters/alien1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:5
      'eventName': "Riddle whittle",
      'imagePath': "assets/images/eventsPosters/astronot.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:6
      'eventName': "Face painting",
      'imagePath': "assets/images/eventsPosters/cosmos1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:7
      'eventName': "Wall painting",
      'imagePath': "assets/images/eventsPosters/womenSinging2.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:8
      'eventName': "Poster making",
      'imagePath': "assets/images/eventsPosters/balloonFight.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
  ],
  [
    //DAY 2
    
    {
      ////index:0
      'eventName': "Origami contest",
      'imagePath': "assets/images/eventsPosters/image_04.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:1
      'eventName': "Draw it now",
      'imagePath': "assets/images/eventsPosters/image_03.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:2
      'eventName': "Card Tower",
      'imagePath': "assets/images/eventsPosters/image_02.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:3
      'eventName': "Tug of war",
      'imagePath': "assets/images/eventsPosters/image_01.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:4
      'eventName': "Arm wrestling",
      'imagePath': "assets/images/eventsPosters/alien1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:5
      'eventName': "Balloon fight",
      'imagePath': "assets/images/eventsPosters/astronot.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:6
      'eventName': "Treasure hunt",
      'imagePath': "assets/images/eventsPosters/cosmos1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:7
      'eventName': "Watch your steps",
      'imagePath': "assets/images/eventsPosters/womenSinging2.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:8
      'eventName': "Antakshari",
      'imagePath': "assets/images/eventsPosters/balloonFight.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
  ],
  [
    //DAY 3
    {
      ////index:0
      'eventName': "Dumb Charades",
      'imagePath': "assets/images/eventsPosters/cosmos1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:1
      'eventName': "Open Mic",
      'imagePath': "assets/images/eventsPosters/image_01.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:2
      'eventName': "Musical Chair",
      'imagePath': "assets/images/eventsPosters/cosmos2.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:3
      'eventName': "Alfaaz",
      'imagePath': "assets/images/eventsPosters/womenSinging2.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:4
      'eventName': "Voice of NIT 2k20",
      'imagePath': "assets/images/eventsPosters/image_04.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:5
      'eventName': "Dance Face off",
      'imagePath': "assets/images/eventsPosters/image_03.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:6
      'eventName': "Short Film making Contest",
      'imagePath': "assets/images/eventsPosters/image_02.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:7
      'eventName': "Tambola House",
      'imagePath': "assets/images/eventsPosters/astronot.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:8
      'eventName': "Ramp Walk",
      'imagePath': "assets/images/eventsPosters/alien1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
  ],
  [ 
    //Miscellaneous Events
    {
      ////index: 0
      'eventName': "PUBG",
      'imagePath': "assets/images/eventsPosters/image_02.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:1
      'eventName': "Call of Duty",
      'imagePath': "assets/images/eventsPosters/image_03.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:2
      'eventName': "Tomclancy’s Rainbow six siege",
      'imagePath': "assets/images/eventsPosters/astronot.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:3
      'eventName': "Dub smash contest",
      'imagePath': "assets/images/eventsPosters/cosmos1.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:4
      'eventName': "Photography contest",
      'imagePath': "assets/images/eventsPosters/womenSinging2.png",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
    {
      ////index:5
      'eventName': "Caption it",
      'imagePath': "assets/images/eventsPosters/image_04.jpg",
      'about':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'rules':"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sit amet volutpat consequat mauris. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Sit amet facilisis magna etiam tempor orci eu lobortis. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet proin. Sapien nec sagittis aliquam malesuada bibendum. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Ultrices gravida dictum fusce ut placerat. Sed risus pretium quam vulputate. Cursus euismod quis viverra nibh cras pulvinar. Metus dictum at tempor commodo ullamcorper. Ut pharetra sit amet aliquam id diam maecenas. Cursus eget nunc scelerisque viverra mauris in. Augue mauris augue neque gravida in fermentum et sollicitudin ac. Nisl nunc mi ipsum faucibus. Nunc id cursus metus aliquam. Enim ut tellus elementum sagittis vitae. Aliquam nulla facilisi cras fermentum odio. Consequat ac felis donec et odio pellentesque diam volutpat commodo.",
      'venue':"nit mai hi kahin khali jgh main ho jaega",
      'coordinators':"2nd year ke 2 ya 3 bande",
      'reg':0
    },
  ],
];
